---
- hosts: all
  become: yes
  tasks:
  - name: instal apache2 server
    dnf:
      name: httpd
      state: present
  - name: start webserver nodes on Redhat
    service:
      name: httpd
      state: started