---
- hosts: all
  become: yes
  tasks:
  - name: instal apache2 server
    dnf:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: start webserver nodes on Redhat
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"